### ISSUE TITLE
Specify file on suit-conformance error

### ISSUE THREAD

**Issue by ghost** [simonsmith/grunt-suitcss#4]
When I use grunt-suitcss to build my components and there is a suit-conformance error, it does not specify the file in which the error was found. Let's say I have the following files:

input.css

``` css
@import "normalize.css";
@import "./MyComponent.css";

@custom-media --narrow-viewport all and (min-width:300px);

:root {
  --color: green;
  --width: 100px;
}

@media (--narrow-viewport) {
  .example {
    /* simple variable */
    color: var(--color);
    /* variable with fallback */
    outline: var(--outline, 1px solid red);
    /* calc */
    width: calc(var(--width) * 2);
  }
}
```

MyComponent.css

``` css
/** @define MyComponent; use strict */

.mistake {
  background: red;
}
```

When building `input.css` to `output.css`, suit-conformance will throw the error: 

```
Fatal error: Invalid selector ".mistake" near line 3:1. Please refer to the SUIT CSS naming conventions: github.com/suitcss/suit.
```

Which does not tell me which file the error was found in. Now it is often not too difficult to find the offending file, but maybe it would be friendlier to log which file the error was encountered in. For large projects this would make finding it a lot easier.

An example would be something like this: https://gist.github.com/ismay/3bcd7825afb59a92477c (which is not exactly the same use case and probably terrible code, so I apologise in advance:).

---

As an aside; I've thought about posting this issue with necolas' rework-suit-conformance, but as that's _meant_ to handle only one file at a time it makes sense for it not to specify the file. So I thought it would be better to tackle this in grunt-suitcss.
